<?php
	echo '<select required name="location">';
	echo '<option value="Byrne House">Byrne House</option>';
	echo '<option value="Champagnat Hall">Champagnat Hall</option>';
	echo '<option value="Cornell Boathouse">Cornell Boathouse</option>';
	echo '<option value="Donnelly Hall">Donnelly Hall</option>';
	echo '<option value="Dyson Center">Dyson Center</option>';
	echo '<option value="Fern Tor">Fern Tor</option>';
	echo '<option value="Fontaine Annex">Fontaine Annex</option>';
	echo '<option value="Fontaine Hall">Fontaine Hall</option>';
	echo '<option value="Foy Townhouses">Foy Townhouses</option>';
	echo '<option value="Fulton Street Townhouses">Fulton Street Townhouses</option>';
	echo '<option value="New Fulton Townhouses">New Fulton Townhouses</option>';
	echo '<option value="Gartland Commons">Gartland Commons</option>';
	echo '<option value="Greystone Hall">GreyStone Hall</option>';
	echo '<option value="Hancock Center">Hancock Center</option>';
	echo '<option value="Kieran Gatehouse">Kieran Gatehouse</option>';
	echo '<option value="Kirk House">Kirk House</option>';
	echo '<option value="Leo Hall">Leo Hall</option>';
	echo '<option value="Library">Library</option>';
	echo '<option value="Longview Park">Longview Park</option>';
	echo '<option value="Lowell Thomas Communication Center">Lowell Thomas Communication Center</option>';
	echo '<option value="Lower Townhouses">Lower Townhouses</option>';
	echo '<option value="Marian Hall">Marian Hall</option>';
	echo '<option value="Marist Boathose">Marist Boathouse</option>';
	echo '<option value="McCann">McCann</option>';
	echo '<option value="Midrise Hall">Midrise Hall</option>';
	echo '<option value="New Townhouses">New Townhouses</option>';
	echo '<option value="St. Peter\'s ">St. Peter\'s</option>';
	echo '<option value="Sheahan Hall">Sheahan Hall</option>';
	echo '<option value="Steel Plant">Steel Plant</option>';
	echo '<option value="Student Center">Student Center</option>';
	echo '<option value="Tenney Stadium">Tenney Stadium</option>';
	echo '<option value="Lower West Cedar Townhouses">Lower West Cedar Townhouses</option>';
	echo '<option value="Upper West Cedar Townhouses">Upper West Cedar Townhouses</option>';
	echo '</select><br>';
?>